package mybatis.dao;

import mybatis.model.Team;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 13 23:57:40 EEST 2021
     */
    //Jeigu norim šitą naudoti reikia eiti ir ieškoti jo xml/TeamMapper.xml
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 13 23:57:40 EEST 2021
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 13 23:57:40 EEST 2021
     */
    Team selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 13 23:57:40 EEST 2021
     */
    List<Team> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 13 23:57:40 EEST 2021
     */
    int updateByPrimaryKey(Team record);
}